In [1]:
import pandas as pd
import numpy as np
dataset = pd.read_csv (r'nbagames.csv')
dataset

Unnamed: 0 Team  Game        Date  Home Opponent WINorLOSS  TeamPoints  \
0              1  ATL     1  10/29/2014  Away      TOR         L         102   
1              2  ATL     2   11/1/2014  Home      IND         W         102   
2              3  ATL     3   11/5/2014  Away      SAS         L          92   
3              4  ATL     4   11/7/2014  Away      CHO         L         119   
4              5  ATL     5   11/8/2014  Home      NYK         W         103   
...          ...  ...   ...         ...   ...      ...       ...         ...   
9835       78119  WAS    78    4/3/2018  Away      HOU         L         104   
9836       79119  WAS    79    4/5/2018  Away      CLE         L         115   
9837       80119  WAS    80    4/6/2018  Home      ATL         L          97   
9838       81124  WAS    81   4/10/2018  Home      BOS         W         113   
9839       82119  WAS    82   4/11/2018  Away      ORL         L          92   

      OpponentPoints  FieldGoals  ...  Opp.FreeThrows  \
0                109          40  ...              27   
1                 92          35  ...              18   
2                 94          38  ...              27   
3                122          43  ...              20   
4                 96          33  ...               8   
...              ...         ...  ...             ...   
9835             120          38  ...              18   
9836             119          47  ...              22   
9837             103          35  ...              16   
9838             101          41  ...              22   
9839             101          33  ...              22   

      Opp.FreeThrowsAttempted  Opp.FreeThrows.  Opp.OffRebounds  \
0                          33            0.818               16   
1                          21            0.857               11   
2                          38            0.711               11   
3                          27            0.741               11   
4                          11            0.727               13   
...                       ...              ...              ...   
9835                       27            0.667               10   
9836                       28            0.786                5   
9837                       23            0.696                7   
9838                       27            0.815               13   
9839                       27            0.815                6   

      Opp.TotalRebounds  Opp.Assists  Opp.Steals  Opp.Blocks  Opp.Turnovers  \
0                    48           26          13           9              9   
1                    44           25           5           5             18   
2                    50           25           7           9             19   
3                    51           31           6           7             19   
4                    44           26           2           6             15   
...                 ...          ...         ...         ...            ...   
9835                 46           26          13           3              9   
9836                 35           26          10           3             16   
9837                 50           24           5           5             18   
9838                 44           22          14           1             16   
9839                 42           20           6           7             16   

      Opp.TotalFouls  
0                 22  
1                 26  
2                 15  
3                 30  
4                 29  
...              ...  
9835              14  
9836              14  
9837              22  
9838              18  
9839              27  

[9840 rows x 41 columns]

In [2]:
clearedDataset = pd.DataFrame(dataset[['Team', 'Assists', 'Steals', 'Blocks', 'Turnovers', 'TeamPoints']])

uniqueTeamsNumber = clearedDataset['Team'].unique()
d = dict(enumerate(uniqueTeamsNumber.flatten(), 1))

def get_key_from_value(d, val):
    keys = [k for k, v in d.items() if v == val]
    if keys:
        return keys[0]
    return None   
    
clearedDataset['Team'] = clearedDataset['Team'].apply(lambda x: get_key_from_value(d, x))
clearedDataset


Team  Assists  Steals  Blocks  Turnovers  TeamPoints
0        1       26       6       8         17         102
1        1       26      10       6         12         102
2        1       26      14       5         13          92
3        1       28       8       3         19         119
4        1       18      10       5          8         103
...    ...      ...     ...     ...        ...         ...
9835    30       25       6       1         17         104
9836    30       34       8       7         15         115
9837    30       18       8       4         12          97
9838    30       32       8       3         20         113
9839    30       17       5       1         12          92

[9840 rows x 6 columns]

In [3]:
X = clearedDataset.drop('TeamPoints',1)
Y = clearedDataset['TeamPoints']
Y

0       102
1       102
2        92
3       119
4       103
       ... 
9835    104
9836    115
9837     97
9838    113
9839     92
Name: TeamPoints, Length: 9840, dtype: int64

In [4]:
from sklearn.model_selection import train_test_split
xTrain, xTest, yTrain, yTest = train_test_split(X,Y,test_size = 0.3, random_state = 1)
print(xTrain.shape)
print(yTrain.shape)
print(xTest.shape)
print(yTest.shape)

(6888, 5)
(6888,)
(2952, 5)
(2952,)


In [5]:
#Algoritmi KNN
from sklearn.neighbors import KNeighborsRegressor 
import sklearn.metrics
from sklearn import metrics
from sklearn.metrics import mean_absolute_error



knn = KNeighborsRegressor(n_neighbors=2)
knn.fit(xTrain, yTrain)
y_pred = knn.predict(xTest)
y_pred
yTestArray = yTest.to_numpy()
print(yTestArray)
print(mean_absolute_error(yTest, y_pred))

print(metrics.max_error(yTest, y_pred))
#print(metrics.explained_variance_score((yTest, y_pred))


[129  91 109 ... 101 102 114]
9.663617886178862
50.5


/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:167: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method

In [6]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

import sklearn.metrics
from sklearn import metrics
DecisionTreeRegModel = DecisionTreeRegressor()
DecisionTreeRegModel = DecisionTreeRegressor()
DecisionTreeRegModel.fit(xTrain, yTrain)
y_pred = DecisionTreeRegModel.predict(xTest)
print(y_pred)
print(metrics.max_error(yTest, y_pred))
print(mean_absolute_error(yTest, y_pred))

[107.  98. 109. ...  91. 100.  91.]
54.0
11.50220189701897


In [7]:
#LogisiticRegression
from sklearn.linear_model import LogisticRegression 
import sklearn.metrics
from sklearn import metrics
from sklearn.metrics import mean_absolute_error
LR = LogisticRegression()
LR.fit(xTrain, yTrain)
y_pred = LR.predict(xTest)
print(y_pred)
print(metrics.max_error(yTest, y_pred))
print(mean_absolute_error(yTest, y_pred))

/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[112 101 106 ...  98 106  98]
50
8.427845528455284
